FROM goatatwork/php-fpm7.1:latest

MAINTAINER Goat

RUN apt-get update \
&& apt-get -y --no-install-recommends install supervisor iputils-ping nano \
&& apt-get clean; rm -rf /var/lib/apt/lists/ /tmp/ /var/tmp/ /usr/share/doc/ \
&& export TERM=xterm

COPY docker/horizon-supervisor/supervisord.conf /etc/supervisord.conf

COPY . /var/www/html

ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
