#!/bin/bash
# 20180406 Goat
# Dnsmasq Webhook for GoldAccess
# Use this with the dnsmasq config paramater
#
# dhcp-script=/usr/local/bin/dhcp-script.sh

#destination="10.200.200.1"
destination="10.13.13.10:8088"

action=${1:-none}
mac=${2:-none}
ip=${3:-none}
hostname=${4:-none}

DNSMASQ_DOMAIN=${DNSMASQ_DOMAIN:-'none'}
DNSMASQ_SUPPLIED_HOSTNAME=${DNSMASQ_SUPPLIED_HOSTNAME:-'none'}
DNSMASQ_TIME_REMAINING=${DNSMASQ_TIME_REMAINING:-'none'}
DNSMASQ_OLD_HOSTNAME=${DNSMASQ_OLD_HOSTNAME:-'none'}
DNSMASQ_INTERFACE=${DNSMASQ_INTERFACE:-'none'}
DNSMASQ_RELAY_ADDRESS=${DNSMASQ_RELAY_ADDRESS:-'none'}
DNSMASQ_TAGS=${DNSMASQ_TAGS:-'none'}
DNSMASQ_LOG_DHCP=${DNSMASQ_LOG_DHCP:-'none'}
DNSMASQ_CLIENT_ID=${DNSMASQ_CLIENT_ID:-'none'}
DNSMASQ_CIRCUIT_ID=${DNSMASQ_CIRCUIT_ID:-'none'}
DNSMASQ_SUBSCRIBER_ID=${DNSMASQ_SUBSCRIBER_ID:-'none'}
DNSMASQ_REMOTE_ID=${DNSMASQ_REMOTE_ID:-'none'}
DNSMASQ_VENDOR_CLASS=${DNSMASQ_VENDOR_CLASS:-'none'}
DNSMASQ_REQUESTED_OPTIONS=${DNSMASQ_REQUESTED_OPTIONS:-'none'}


generate_post_data()
{
    echo "{\"ACTION\": \"$action\",\"HOSTMAC\":\"$mac\",\"IP\":\"$ip\",\"HOSTNAME\":\"$hostname\",\"DNSMASQ_DOMAIN\":\"$DNSMASQ_DOMAIN\",\"DNSMASQ_SUPPLIED_HOSTNAME\":\"$DNSMASQ_SUPPLIED_HOSTNAME\",\"DNSMASQ_TIME_REMAINING\":\"$DNSMASQ_TIME_REMAINING\",\"DNSMASQ_OLD_HOSTNAME\":\"$DNSMASQ_OLD_HOSTNAME\",\"DNSMASQ_INTERFACE\":\"$DNSMASQ_INTERFACE\",\"DNSMASQ_RELAY_ADDRESS\":\"$DNSMASQ_RELAY_ADDRESS\",\"DNSMASQ_TAGS\":\"$DNSMASQ_TAGS\",\"DNSMASQ_LOG_DHCP\":\"$DNSMASQ_LOG_DHCP\",\"DNSMASQ_CLIENT_ID\":\"$DNSMASQ_CLIENT_ID\",\"DNSMASQ_CIRCUIT_ID\":\"$DNSMASQ_CIRCUIT_ID\",\"DNSMASQ_SUBSCRIBER_ID\":\"$DNSMASQ_SUBSCRIBER_ID\",\"DNSMASQ_REMOTE_ID\":\"$DNSMASQ_REMOTE_ID\",\"DNSMASQ_VENDOR_CLASS\":\"$DNSMASQ_VENDOR_CLASS\",\"DNSMASQ_REQUESTED_OPTIONS\":\"$DNSMASQ_REQUESTED_OPTIONS\"}"
}

curl -i \
-H "Accept: application/json" \
-H "Content-Type:application/json" \
-H "X-CSRF-TOKEN:LGri4hy2pGlx9wVpVvVqTHRwwavZVn2vYu2PS4a2" \
-X POST --data "$(generate_post_data)" "http://$destination/api/dnsmasq/events"
